version: "3.9"
services:
  app:
    image: app:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habit-or-die
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
