version: "3.9"

services:

  app:
    image: app:latest
    build:
      dockerfile: Dockerfile
    depends_on:
        - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habitordie

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

  mongo:
      image: mongo
      restart: always
      ports:
          - "27017:27017"
      environment:
          MONGO_INITDB_DATABASE: habitordie
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
      image: mongo-express
      restart: always
      ports:
          - "8081:8081"
      environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
          ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
          ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
          ME_CONFIG_BASICAUTH: false

  prometheus:
    image: prom/prometheus
    depends_on:
      - app
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
