version: "3.9"
services:
  app:
    image: app:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habitordie

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus
    depends_on:
      - app
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
