spring:
  application:
    name: habit-or-die
  datasource:
    url: jdbc:postgresql://localhost:5432/habitordie
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: habitordie
      username: mongo
      password: mongo
      authentication-database: admin
  banner:
    location: static/banner.txt

app:
  jwt:
    key: 7c3c2951317a444f32556f6d56242d753020743751596135642d432e3c
    algorithm: HS256
    issuer: http://localhost:8080
    expires-in: 24h
  file:
    upload:
      max-size: 15728640
      allowed-types: image/jpeg,image/png

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

server:
  error:
    include-message: always
