scrape_configs:
  - job_name: 'Habit or Die Metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Habit or Die'
