name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_NAME: habit-or-die
  JAVA_VERSION: 21
  DISTRIBUTION: 'temurin'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate branch name
        run: |
          branch_name=${BRANCH_NAME}
          pattern="^(feature|bugfix|hotfix|release|experiment|task|epic|story|improvement|chore)\/HD-[0-9]+(-[a-z0-9-]+)?( [a-z0-9]+)*$"
          
          if ! [[ $branch_name =~ $pattern ]]; then
            echo "Error: Branch name '$branch_name' does not match the required naming convention."
            echo "Pattern: $pattern"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-branch-name

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build the project
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run the tests
        run: ./gradlew test