name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_NAME: habit-or-die
  JAVA_VERSION: 21
  DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build the project
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run the tests
        run: ./gradlew test